In [1]:
import pandas as pd
import numpy as np 
import pickle 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
plt.rcParams['font.sans-serif'] = ['Microsoft JHenghei']
plt.rcParams['axes.unicode_minus'] = False

In [3]:
get = pickle.load(open('simulation_data/parameters_0.pkl','rb'))

In [4]:
data = pd.read_csv('simulation_data/data_0.csv')

In [5]:
X = data.iloc[:,:5]

In [6]:
T_beta = get['beta']

In [7]:
simu_beta = pd.read_csv('1000_times_beta.csv')
simu_beta

0         1         2         3         4
0    0.113609  0.258837 -2.011771  0.550795 -0.947591
1    0.087067  0.275175 -2.033782  0.561976 -0.927727
2    0.085115  0.281885 -2.014799  0.551407 -0.939983
3    0.105462  0.266751 -2.028268  0.560287 -0.941265
4    0.095538  0.331232 -2.041432  0.526267 -0.948511
..        ...       ...       ...       ...       ...
995  0.059735  0.324237 -2.003103  0.531372 -0.949009
996  0.066096  0.276824 -2.037593  0.558110 -0.899351
997  0.108072  0.326746 -2.056757  0.532892 -0.947813
998  0.095561  0.285598 -2.034967  0.536728 -0.920497
999  0.098609  0.283969 -2.046127  0.560278 -0.933900

[1000 rows x 5 columns]

In [8]:
B = np.repeat(5,5)
B = B.reshape(5,1)
B = np.dot(B,B.T)

B = B + np.eye(5)

In [9]:
B

array([[26., 25., 25., 25., 25.],
       [25., 26., 25., 25., 25.],
       [25., 25., 26., 25., 25.],
       [25., 25., 25., 26., 25.],
       [25., 25., 25., 25., 26.]])

In [10]:
T_beta

array([ 0.09467958,  0.27820584, -2.07799018,  0.53026507, -0.96156416])

In [11]:
(simu_beta - T_beta)

0         1         2         3         4
0    0.018930 -0.019369  0.066219  0.020530  0.013974
1   -0.007613 -0.003030  0.044209  0.031711  0.033837
2   -0.009564  0.003680  0.063191  0.021142  0.021581
3    0.010782 -0.011455  0.049722  0.030021  0.020299
4    0.000859  0.053026  0.036558 -0.003998  0.013053
..        ...       ...       ...       ...       ...
995 -0.034945  0.046031  0.074887  0.001107  0.012555
996 -0.028584 -0.001381  0.040398  0.027845  0.062214
997  0.013392  0.048540  0.021233  0.002627  0.013751
998  0.000881  0.007393  0.043023  0.006463  0.041068
999  0.003929  0.005763  0.031863  0.030013  0.027664

[1000 rows x 5 columns]

In [12]:
V = (simu_beta - T_beta)*np.sqrt(50000)

In [13]:
V.describe()

0            1            2            3            4
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean      1.697788     1.842149    10.913407     1.075208     6.710048
std       4.100544     4.048841     3.999101     4.187275     4.086293
min     -10.283260    -9.381013    -0.275892   -13.361404    -4.993551
25%      -1.097081    -0.941946     8.268191    -1.588668     3.881262
50%       1.520041     1.950530    10.932491     1.162952     6.786251
75%       4.566904     4.552167    13.670146     3.888513     9.541076
max      13.522220    13.580041    22.668327    13.166853    20.436300

In [14]:
V.cov()

0          1          2          3          4
0  16.814458  -3.621806  -3.865386  -4.336637  -4.979729
1  -3.621806  16.393116  -4.611862  -4.515419  -3.672842
2  -3.865386  -4.611862  15.992807  -4.091299  -3.438462
3  -4.336637  -4.515419  -4.091299  17.533271  -4.577788
4  -4.979729  -3.672842  -3.438462  -4.577788  16.697793

In [15]:
np.linalg.inv(B)

array([[ 0.8015873, -0.1984127, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127,  0.8015873, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127,  0.8015873, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127,  0.8015873, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127, -0.1984127,  0.8015873]])