In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook

# 同一組資料 SGD

In [4]:
class SGD_ASGD_linear():
  
    def train(self,epoch,n,dim,lr,alpha,param_fix=True):

        if param_fix:
            np.random.seed(2021)
            self.true_theta = np.random.randn(dim)
            np.random.seed()
        else:
            self.true_theta = np.random.randn(dim)
        
        self.x = np.random.normal(loc=5,scale=1,size=(n,dim))
        self.y = np.dot(self.x,self.true_theta)+np.random.randn()
        
        self.SGD = list()
        self.ASGD = list()
        
        
        for m in tqdm_notebook(range(epoch)):
            
            self.theta_hat =[]
            theta_hat = np.random.randn(len(self.true_theta))
            
            sample = np.random.choice(a=range(n),size=n,replace=True)
            
            count = 0
            for i in sample:    
                
                lr_now = lr*pow(count+1,-alpha)

                coef = np.linalg.inv(np.eye(dim)+lr_now*np.dot(self.x[i].reshape(dim,-1),self.x[i].reshape(-1,dim)))

                theta_hat = np.dot(coef,theta_hat) + np.dot(coef,lr_now*self.y[i]*self.x[i])

                self.theta_hat.append(theta_hat)
                count += 1

            self.SGD.append(self.theta_hat[-1])
            self.ASGD.append(np.mean(self.theta_hat,axis=0))
            

In [5]:
n = 10000
dim = 5
lr = 10
alpha = 0.6
epoch = 100

In [6]:
result = SGD_ASGD_linear()
result.train(epoch,n,dim,lr,alpha)

In [7]:
result.true_theta

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081,  0.55587583])

In [8]:
result.ASGD

[array([ 1.4606887 ,  0.64983635, -0.41095248, -0.80261235,  0.52876555]),
 array([ 1.46188696,  0.67041164, -0.43328604, -0.80456842,  0.53005757]),
 array([ 1.44843661,  0.66339414, -0.41178278, -0.81117386,  0.5365923 ]),
 array([ 1.45288068,  0.6658784 , -0.41170425, -0.82766716,  0.54573448]),
 array([ 1.45233035,  0.65113576, -0.42517186, -0.82101148,  0.56802584]),
 array([ 1.44945409,  0.66236936, -0.43630358, -0.78725928,  0.53660035]),
 array([ 1.47244159,  0.6742518 , -0.44858746, -0.81394112,  0.54141276]),
 array([ 1.45413426,  0.66194797, -0.4115521 , -0.81260586,  0.53358167]),
 array([ 1.45087285,  0.6608614 , -0.41813672, -0.80003225,  0.53326771]),
 array([ 1.46123332,  0.64642335, -0.40626821, -0.83118654,  0.55519983]),
 array([ 1.44786576,  0.67673993, -0.42921382, -0.81470116,  0.54459601]),
 array([ 1.47018517,  0.66373622, -0.42703712, -0.81220086,  0.53068677]),
 array([ 1.47482695,  0.64953238, -0.42078506, -0.81244093,  0.53459369]),
 array([ 1.43900497,  0.6

In [9]:
10000*pd.DataFrame(result.ASGD).cov()

0         1         2         3         4
0  1.803201 -0.592252 -0.456632 -0.087623 -0.667225
1 -0.592252  1.406390 -0.210245 -0.390039 -0.226269
2 -0.456632 -0.210245  1.533317 -0.511766 -0.342503
3 -0.087623 -0.390039 -0.511766  1.244869 -0.260875
4 -0.667225 -0.226269 -0.342503 -0.260875  1.505280

In [10]:
true = np.repeat(5,5)
true= true.reshape(5,1)
true = np.dot(true,true.T)
true = true + np.eye(5)
true = np.linalg.inv(true)

In [11]:
true

array([[ 0.8015873, -0.1984127, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127,  0.8015873, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127,  0.8015873, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127,  0.8015873, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127, -0.1984127,  0.8015873]])

# 每次生成新資料

In [29]:
class SGD_ASGD_linear2():
    
    def train(self,epoch,n,dim,lr,alpha,param_fix=True):
        if param_fix:
            np.random.seed(2021)
            self.true_theta = np.random.randn(dim)
            np.random.seed()
        else:
            self.true_theta = np.random.randn(dim)

        self.SGD = list()
        self.ASGD = list()

        for m in tqdm_notebook(range(epoch)):

            self.theta_hat =[]
            theta_hat = np.random.randn(len(self.true_theta))
            for i in range(n):

                lr_now = lr*pow(i+1,-alpha)
                x = np.random.normal(loc=5,scale=1,size=dim)
                y = np.dot(self.true_theta,x)+np.random.randn()
                coef = np.linalg.inv(np.eye(dim)+lr_now*np.dot(x.reshape(dim,-1),x.reshape(-1,dim)))
                
                theta_hat = np.dot(coef,theta_hat) + np.dot(coef,lr_now*y*x)
                self.theta_hat.append(theta_hat)

            self.SGD.append(self.theta_hat[-1])
            self.ASGD.append(np.mean(self.theta_hat,axis=0))

In [30]:
n = 10000
dim = 5
lr = 10
alpha = 0.6
epoch = 100

In [31]:
result2 = SGD_ASGD_linear2()
result2.train(epoch,n,dim,lr,alpha)

In [32]:
result2.true_theta

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081,  0.55587583])

In [33]:
result2.ASGD

[array([ 1.47838244,  0.68242835, -0.42028369, -0.79244566,  0.54615091]),
 array([ 1.48030308,  0.68272167, -0.39883872, -0.80693364,  0.5422275 ]),
 array([ 1.46683229,  0.64505398, -0.35928953, -0.80912837,  0.5504712 ]),
 array([ 1.47873385,  0.64686872, -0.40817191, -0.7819588 ,  0.5610243 ]),
 array([ 1.44953655,  0.70074266, -0.39500707, -0.80320382,  0.54363053]),
 array([ 1.46803048,  0.68495519, -0.39039624, -0.81427794,  0.54599634]),
 array([ 1.45304247,  0.65511729, -0.41911686, -0.77554584,  0.57809326]),
 array([ 1.47668857,  0.69947184, -0.44188773, -0.77885895,  0.54300056]),
 array([ 1.48895453,  0.63704369, -0.39033372, -0.80554826,  0.57069119]),
 array([ 1.4871472 ,  0.6648495 , -0.40661789, -0.7972355 ,  0.54572375]),
 array([ 1.49476045,  0.63854435, -0.43408208, -0.7891873 ,  0.58702371]),
 array([ 1.45800895,  0.6637526 , -0.37904241, -0.78008432,  0.53169822]),
 array([ 1.49668082,  0.68099845, -0.42866687, -0.79855274,  0.54809492]),
 array([ 1.47463047,  0.6

In [34]:
10000*pd.DataFrame(result2.ASGD).cov()

0         1         2         3         4
0  2.748128 -0.652026 -0.904021 -1.017568 -0.115959
1 -0.652026  3.024107 -0.914553 -0.826626 -0.592815
2 -0.904021 -0.914553  3.689254 -0.684278 -1.179713
3 -1.017568 -0.826626 -0.684278  3.457970 -0.955551
4 -0.115959 -0.592815 -1.179713 -0.955551  2.823445

In [35]:
true = np.repeat(5,5)
true= true.reshape(5,1)
true = np.dot(true,true.T)
true = true + np.eye(5)
true = np.linalg.inv(true)

In [36]:
true

array([[ 0.8015873, -0.1984127, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127,  0.8015873, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127,  0.8015873, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127,  0.8015873, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127, -0.1984127,  0.8015873]])