In [1]:
import numpy as np
import pandas as pd

from tqdm import tqdm_notebook

# 同樣一組data 抽樣sgd

In [2]:
class SGD_ASGD_linear():
    
    def train(self,epoch,n,dim,lr,alpha,param_fix=True):
        
        if param_fix:
            np.random.seed(2021)
            self.true_theta = np.random.randn(dim)
            np.random.seed()
        else:
            self.true_theta = np.random.randn(dim)
        
        self.x = np.random.normal(loc=5,scale=1,size=(n,dim))
        self.y = np.dot(self.x,self.true_theta)+np.random.randn()
        
        self.SGD = list()
        self.ASGD = list()
        
        
        for m in tqdm_notebook(range(epoch)):
            
            self.theta_hat =[]
            theta_hat = np.random.randn(len(self.true_theta))
            
            sample = np.random.choice(a=range(n),size=n,replace=True)
            
            count = 0
            for i in sample:    
                
                lr_now = lr*pow(count+1,-alpha)

                coef = np.linalg.inv(np.eye(dim)+lr_now*np.dot(self.x[i].reshape(dim,-1),self.x[i].reshape(-1,dim)))

                theta_hat = np.dot(coef,theta_hat) + np.dot(coef,lr_now*self.y[i]*self.x[i])

                self.theta_hat.append(theta_hat)
                count += 1

            self.SGD.append(self.theta_hat[-1])
            self.ASGD.append(np.mean(self.theta_hat,axis=0))
            
            

In [3]:
n = 10000
dim = 5
lr = 10
alpha = 0.6
epoch = 100

In [4]:
result = SGD_ASGD_linear()
result.train(epoch,n,dim,lr,alpha)

In [5]:
result.true_theta

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081,  0.55587583])

In [6]:
result.ASGD

[array([ 1.50840873,  0.71366873, -0.37015176, -0.75002101,  0.58731004]),
 array([ 1.52182076,  0.68775614, -0.37688513, -0.73702364,  0.5939539 ]),
 array([ 1.52429689,  0.72406102, -0.37995494, -0.74021023,  0.56055439]),
 array([ 1.51873239,  0.70855736, -0.38297892, -0.74472753,  0.5894121 ]),
 array([ 1.51712947,  0.71965358, -0.36872761, -0.78331876,  0.60433908]),
 array([ 1.50357152,  0.71787389, -0.359868  , -0.75296544,  0.58125119]),
 array([ 1.52892317,  0.69336592, -0.36687927, -0.76163671,  0.59558599]),
 array([ 1.50317469,  0.71698451, -0.37770768, -0.75497311,  0.60221262]),
 array([ 1.52451286,  0.71061112, -0.38136588, -0.75990926,  0.59549643]),
 array([ 1.51451366,  0.7100865 , -0.36660483, -0.77036277,  0.60204392]),
 array([ 1.497715  ,  0.69654655, -0.36947791, -0.74931439,  0.61359305]),
 array([ 1.50103191,  0.70761314, -0.37810662, -0.74627818,  0.60585844]),
 array([ 1.51676417,  0.71269718, -0.37767418, -0.76312867,  0.60044165]),
 array([ 1.4967346 ,  0.7

In [7]:
10000*pd.DataFrame(result.ASGD).cov()

0         1         2         3         4
0  1.672177 -0.535963 -0.477047 -0.458265 -0.198176
1 -0.535963  1.389093 -0.332629  0.105919 -0.622021
2 -0.477047 -0.332629  1.375674 -0.296674 -0.266868
3 -0.458265  0.105919 -0.296674  1.328816 -0.677145
4 -0.198176 -0.622021 -0.266868 -0.677145  1.753910

In [8]:
true = np.repeat(5,5)
true= true.reshape(5,1)
true = np.dot(true,true.T)

true = true + np.eye(5)
true = np.linalg.inv(true)

In [9]:
true

array([[ 0.8015873, -0.1984127, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127,  0.8015873, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127,  0.8015873, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127,  0.8015873, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127, -0.1984127,  0.8015873]])

# 每次生成不同data進行迭代

In [10]:
class SGD_ASGD_linear2():
    
    def train(self,epoch,n,dim,lr,alpha,param_fix=True):
        
        if param_fix:
            np.random.seed(2021)
            self.true_theta = np.random.randn(dim)
            np.random.seed()
        else:
            self.true_theta = np.random.randn(dim)
        
       
        
        self.SGD = list()
        self.ASGD = list()
        
        for m in tqdm_notebook(range(epoch)):
            
            self.theta_hat =[]
            theta_hat = np.random.randn(len(self.true_theta))
            for i in range(n):
                
                lr_now = lr*pow(i+1,-alpha)
                x = np.random.normal(loc=5,scale=1,size=dim)
                y = np.dot(self.true_theta,x)+np.random.randn()
                coef = np.linalg.inv(np.eye(dim)+lr_now*np.dot(x.reshape(dim,-1),x.reshape(-1,dim)))
                theta_hat = np.dot(coef,theta_hat) + np.dot(coef,lr_now*y*x)

                self.theta_hat.append(theta_hat)

            self.SGD.append(self.theta_hat[-1])
            self.ASGD.append(np.mean(self.theta_hat,axis=0))
            
            

In [11]:
n = 10000
dim = 5
lr = 10
alpha = 0.6
epoch = 100

In [12]:
result2 = SGD_ASGD_linear2()
result2.train(epoch,n,dim,lr,alpha)

In [13]:
result2.true_theta

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081,  0.55587583])

In [14]:
10000*pd.DataFrame(result2.ASGD).cov()

0         1         2         3         4
0  2.889850 -0.462595 -0.753553 -0.841729 -0.828008
1 -0.462595  2.519848 -0.581295 -0.407049 -1.105673
2 -0.753553 -0.581295  2.272752 -0.694493 -0.207994
3 -0.841729 -0.407049 -0.694493  2.592966 -0.614888
4 -0.828008 -1.105673 -0.207994 -0.614888  2.764238

In [15]:
true = np.repeat(5,5)
true= true.reshape(5,1)
true = np.dot(true,true.T)

true = true + np.eye(5)
true = np.linalg.inv(true)

In [16]:
true

array([[ 0.8015873, -0.1984127, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127,  0.8015873, -0.1984127, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127,  0.8015873, -0.1984127, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127,  0.8015873, -0.1984127],
       [-0.1984127, -0.1984127, -0.1984127, -0.1984127,  0.8015873]])